name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Seems like this is your first issue here. Make sure to read the contributing guidelines and follow them here.'
        pr-message: 'Seems like your first PR here. Wait for us to get back to you, meanwhile make sure you have followed contributing guidelines and then sit back and chill!'
